sonar.projectKey=excaliterm
sonar.projectName=excaliterm
sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/bin/**,**/obj/**,**/coverage/**,**/*.test.*,**/*.spec.*,**/screenshots/**,**/data/**,**/pnpm-lock.yaml
sonar.sourceEncoding=UTF-8
sonar.cs.file.suffixes=.cs
sonar.typescript.file.suffixes=.ts,.tsx
